name: kasie_transie_web
description: Kasie Transie Web Admin

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

#  kasie_transie_library:
#    path: ../kasie_transie_library
  cupertino_icons: ^1.0.5
  flutter_local_notifications: ^15.1.0+1
  firebase_auth: ^4.7.2
#  firebase_messaging: ^14.6.3
#  firebase_core: ^2.14.0
#  firebase_storage: ^11.2.3
  firebase_messaging: ^14.6.5
  animated_splash_screen: ^1.3.0
  font_awesome_flutter: ^10.4.0
  google_maps_flutter: ^2.4.0
  page_transition: ^2.0.9
  responsive_builder: ^0.7.0
  flutter_riverpod: ^2.3.6
  pretty_json: ^2.0.0
  geolocator: ^9.0.2
  focused_menu: ^1.0.5
  firebase_ui_auth: ^1.6.2
  intl: ^0.18.0
  workmanager: ^0.5.1
  dots_indicator: ^3.0.0
  uuid: ^3.0.7
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.0
  json_annotation: ^4.8.1
  universal_io: ^2.2.2
  archive: ^3.3.7
  account_picker: ^2.1.0
  sms_autofill: ^2.3.0
  numeric_keyboard: ^1.1.0
  mobile_number: ^2.1.1
  flutter_analog_clock: ^1.0.3
  custom_map_markers: ^0.0.2+1
  google_maps_cluster_manager: ^3.0.0+1
  fluttertoast: ^8.2.2
  google_fonts: ^5.1.0
  image: ^4.0.17
  badges: ^3.1.1
  google_maps_flutter_web: ^0.5.3
  animations: ^2.0.7
  flex_color_scheme: ^7.2.0



#  background_location: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.6
  json_serializable: ^6.7.1


flutter:

  uses-material-design: true

  assets:
    - assets/intro/
    - assets/mapicons/
    - assets/l10n/
    - assets/
    - assets/projects/
    - assets/payment/
    - assets/markers/
    - assets/numbers/
    - .env
